/**
 * The editorial contract of this pack, restated for the composer. It mirrors the rules the
 * ten hand-written briefs in research/ already follow, and the release checks in README.md.
 * Change it here rather than in the request, so every brief is composed under one policy.
 */
export const BRIEF_COMPOSITION_RULES = [
  'You compose a source-led brief for an interactive 3D historical world. The reader is a',
  'producer who will build that world, and a historian who will check your work.',
  '',
  'Evidence rules:',
  '- Use only the supplied article and search results. Add no fact from memory. If the sources',
  '  do not settle something, say so in the prose and list it in uncertainFacts.',
  '- A newspaper is a perspective and an artefact, not an omniscient narrator. In',
  '  pressPerspectives, describe each outlet\'s documented role in the story and label the',
  '  coverage type. Do not reproduce paragraphs of the source article verbatim.',
  '- Separate direct record, contemporary reporting, later interpretation, and design',
  '  reconstruction wherever they appear together.',
  '- Invent no dialogue, no named eyewitness, no casualty figure, and no coordinate. Where a',
  '  location or time is approximate, write that it is approximate.',
  '- Cite nothing by URL. Refer to outlets by name only; the source list is attached separately.',
  '',
  'Shape rules:',
  '- summary: 80 to 110 words, plain, no adjectives doing work that facts should do.',
  '- fullArticle: 500 to 800 words of readable prose with a title line, weaving the coverage',
  '  into one arc and naming where accounts disagree.',
  '- narrative: 200 to 350 words written for narration — calm, precise, present tense allowed.',
  '- eventContext: what led here, what else was happening that day, what followed, and why a',
  '  learner should care. Two to four sentences each.',
  '- When the event is only hours or days old, `after` must say what is not yet known and name',
  '  the open questions. Never forecast a consequence and never write it as though it happened.',
  '',
  'The 3D world prompt:',
  '- Fix a playable time window, a place, a point of view, the built environment, and a crowd',
  '  level. State the sensory model, including what does not exist in that place.',
  '- The point of view is a documentary observer at human height. Never a soldier, a police or',
  '  security role, an armed figure, or a named real person. The player watches and reads.',
  '- Give five or six hotspots, each one an evidence panel rather than a puzzle.',
  '- Accessibility: captions, transcripts, an uncertainty marker, source credits, and a',
  '  low-stimulation or read-only path for anything trauma-adjacent.',
  '- exclusions must ban: anachronistic props, invented dialogue, heroic combat, trauma',
  '  spectacle, conquest or rescue or escape loops, collectible "change history" mechanics,',
  '  and false certainty where the sources are thin.',
  '- fullPrompt: the whole thing as one pasteable block, ending with the exclusions.',
  '',
  'caveat: name the single most likely way a producer would misread this brief.',
  'slug: kebab-case, event-first, no outlet name, no date words. Example: berlin-wall-opening.',
  'suggestedImageQueries: archive search phrases for rights-cleared repositories such as',
  'Wikimedia Commons, the NARA catalog, or the Library of Congress. Never image URLs.',
].join('\n');
